const property: CarProperty = {
  name: 'power source',
  columnName: 'kayttovoima',
  valueLabels: {
    '01': { fi: 'Bensiini', sv: 'Bensin', en: 'Petrol' },
    '02': { fi: 'Dieselöljy', sv: 'Dieselolja', en: 'Diesel fuel' },
    '03': { fi: 'Polttoöljy', sv: 'Brännolja', en: 'Fuel oil' },
    '04': { fi: 'Sähkö', sv: 'Elektricitet', en: 'Electricity' },
    '05': { fi: 'Vety', sv: 'Hydrogen', en: 'Hydrogen' },
    '06': { fi: 'Kaasu', sv: 'Gas', en: 'Gas' },
    '07': { fi: 'Metanoli', sv: 'Metanol', en: 'Methanol' },
    10: { fi: 'Biodiesel', sv: 'Biodiesel', en: 'Biodiesel fuel' },
    11: { fi: 'LPG', sv: 'LPG', en: 'LPG' },
    13: { fi: 'CNG', sv: 'CNG', en: 'CNG' },
    31: { fi: 'Moottoripetroli', sv: 'Motorfotogen', en: 'Light fuel oil (kerosene)' },
    32: { fi: 'Diesel/Puu', sv: 'Diesel/Trä', en: 'Diesel/wood' },
    33: { fi: 'Bensiini/Puu', sv: 'Bensin/Trä', en: 'Petrol/wood' },
    34: { fi: 'Bensiini + moottoripetroli', sv: 'Bensin + motorfotogen', en: 'Petrol + light fuel oil (kerosene)' },
    37: { fi: 'Etanoli', sv: 'Etanol', en: 'Ethanol' },
    38: { fi: 'Bensiini/CNG', sv: 'Bensin/CNG', en: 'Petrol/CNG' },
    39: { fi: 'Bensiini/Sähkö', sv: 'Bensin/Elektricitet', en: 'Petrol/Electricity' },
    40: { fi: 'Bensiini/Etanoli', sv: 'Bensin/Etanol', en: 'Petrol/Ethanol' },
    41: { fi: 'Bensiini/Metanoli', sv: 'Bensin/Metanol', en: 'Petrol/Methanol' },
    42: { fi: 'Bensiini/LPG', sv: 'Bensin/LPG', en: 'Petrol/LPG' },
    43: { fi: 'Diesel/CNG', sv: 'Diesel/CNG', en: 'Diesel fuel / CNG' },
    44: { fi: 'Diesel/Sähkö', sv: 'Diesel/Elektricitet', en: 'Diesel fuel / Electricity' },
    45: { fi: 'Diesel/Etanoli', sv: 'Diesel/Etanol', en: 'Diesel fuel / Ethanol' },
    46: { fi: 'Diesel/Metanoli', sv: 'Diesel/Metanol', en: 'Diesel fuel / Methanol' },
    47: { fi: 'Diesel/LPG', sv: 'Diesel/LPG', en: 'Diesel fuel / LPG' },
    48: { fi: 'Diesel/Biodiesel', sv: 'Diesel/Biodiesel', en: 'Diesel fuel / Biodiesel fuel' },
    49: {
      fi: 'Diesel/Biodiesel/Sähkö',
      sv: 'Diesel/Biodiesel/Elektricitet',
      en: 'Diesel fuel / Biodiesel fuel / Electricity',
    },
    50: {
      fi: 'Diesel/Biodiesel/Etanoli',
      sv: 'Diesel/Biodiesel/Etanol',
      en: 'Diesel fuel / Biodiesel fuel / Ethanol',
    },
    51: {
      fi: 'Diesel/Biodiesel/Metanoli',
      sv: 'Diesel/Biodiesel/Metanol',
      en: 'Diesel fuel / Biodiesel fuel / Methanol',
    },
    52: { fi: 'Diesel/Biodiesel/LPG', sv: 'Diesel/Biodiesel/LPG', en: 'Diesel fuel / Biodiesel fuel / LPG' },
    53: { fi: 'Diesel/Biodiesel/CNG', sv: 'Diesel/Biodiesel/CNG', en: 'Diesel fuel / Biodiesel fuel / CNG' },
    54: { fi: 'Vety/Sähkö', sv: 'Hydrogen/Elektricitet', en: 'Hydrogen/Electricity' },
    55: { fi: 'Dieselöljy/Muu', sv: 'Dieselolja/Övrig', en: 'Diesel fuel / Other' },
    56: { fi: 'H-ryhmän maakaasu', sv: 'Naturgastyp H', en: 'Natural gas type H' },
    57: { fi: 'L-ryhmän maakaasu', sv: 'Naturgastyp L', en: 'Natural gas type L' },
    58: { fi: 'HL-ryhmän maakaasu', sv: 'Naturgastyp HL', en: 'Natural gas type HL' },
    59: { fi: 'CNG/Biometaani', sv: 'CNG/Biometan', en: 'Natural gas / Biomethane' },
    60: { fi: 'Biometaani', sv: 'Biometan', en: 'Biomethan' },
    61: { fi: 'Puu', sv: 'Träd', en: 'Wood' },
    62: { fi: 'Etanoli (ED95)', sv: 'Etanol (ED95)', en: 'Ethanol (ED95)' },
    63: { fi: 'Etanoli (E85)', sv: 'Etanol (E85)', en: 'Ethanol (E85)' },
    64: { fi: 'Vety-maakaasuseos', sv: 'H2NG-blandning', en: 'H2NG' },
    65: { fi: 'LNG', sv: 'LNG', en: 'LNG' },
    66: { fi: 'LNG20', sv: 'LNG20', en: 'LNG20' },
    67: { fi: 'Diesel/LNG', sv: 'Diesel/LNG', en: 'Diesel/LNG' },
    68: { fi: 'Diesel/LNG20', sv: 'Diesel/LNG20', en: 'Diesel/LNG20' },
    X: { fi: 'Ei sovellettavissa', sv: 'Ej tillämplig', en: 'Not applicable' },
    Y: { fi: 'Muu', sv: 'Övrig', en: 'Other' },
  },
};

export = property;
